name: Backend CI

on:
  push:
    branches: [ main, dev ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create .env file from ENV_DEV secret
        run: |
          echo "${{ secrets.ENV_DEV }}" > .env

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t 1-load-test-be:latest .
          docker push 1-load-test-be:latest